swagger: '2.0'
info:
  version: '1.0'
  title: API CRUD DE VEICULO
  contact: {}
basePath: /api-veiculo
schemes:
- https
- http
consumes:
- application/json
produces:
- application/json
paths:
  /veiculo:
    get:
      summary: Listar Veículos
      tags:
      - Veículo
      operationId: ListarVeículos
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: array
            items:
              $ref: '#/definitions/ObterVeiculoResponse'
        '400':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/MensagemResponse'
    post:
      summary: Criar Veículo
      tags:
      - Veículo
      operationId: CriarVeículo
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CriarVeiculoRequest'
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/MensagemResponse'
        '400':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/MensagemResponse'
    put:
      summary: Atualizar Veículo
      tags:
      - Veículo
      operationId: AtualizarVeículo
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/AtualizarVeiculoRequest'
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/MensagemResponse'
        '400':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/MensagemResponse'
  /veiculo/{placa}:
    delete:
      summary: Deletar Veículo
      tags:
      - Veículo
      operationId: DeletarVeículo
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: placa
        in: path
        required: true
        type: string
        description: ''
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/MensagemResponse'
        '400':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/MensagemResponse'
    get:
      summary: Obter Veículo
      tags:
      - Veículo
      operationId: ObterVeículo
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: placa
        in: path
        required: true
        type: string
        description: ''
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/ObterVeiculoResponse'
        '400':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/MensagemResponse'
definitions:
  CriarVeiculoRequest:
    title: CriarVeiculoRequest
    example:
      placa: AAA1234
      chassi: 1RV 524T98 88 S92605
      renavam: '98447225015'
      modelo: Del Rey Belina GL
      marca: Ford
      ano: 1987
    type: object
    properties:
      placa:
        type: string
      chassi:
        type: string
      renavam:
        type: string
      modelo:
        type: string
      marca:
        type: string
      ano:
        type: integer
        format: int32
    required:
    - placa
    - chassi
    - renavam
    - modelo
    - marca
    - ano

  AtualizarVeiculoRequest:
    title: AtualizarVeiculoRequest
    example:
      placa: AAA1234
      chassi: 1RV 524T98 88 S92605
      renavam: '98447225015'
      modelo: Del Rey Belina GL
      marca: Ford
      ano: 1988
    type: object
    properties:
      placa:
        type: string
      chassi:
        type: string
      renavam:
        type: string
      modelo:
        type: string
      marca:
        type: string
      ano:
        type: integer
        format: int32
    required:
    - placa
    - chassi
    - renavam
    - modelo
    - marca
    - ano

  ObterVeiculoResponse:
    title: ObterVeiculoResponse
    example:
      id: 1
      placa: AAA1234
      chassi: 1RV 524T98 88 S92605
      renavam: '98447225015'
      modelo: Del Rey Belina GL
      marca: Ford
      ano: 1988
    type: object
    properties:
      id:
        type: integer
        format: int32
      placa:
        type: string
      chassi:
        type: string
      renavam:
        type: string
      modelo:
        type: string
      marca:
        type: string
      ano:
        type: integer
        format: int32

  MensagemResponse:
    title: MensagemResponse
    type: object
    properties:
      mensagem:
        type: string
        
tags:
- name: Veículo
  description: ''